### ISSUE TITLE
[BE] Trip Management

### ISSUE THREAD

**Issue by OfekShimko** [OfekShimko/TripNest#23]
1. Implement trip creation, including name and date range.
2. Develop functionality to add activities to trips.

**Comment by OBaca** [comment]
1. POST api/v1/trips/
Its working - created new trip by the values: 
title || description || location || from_date || to_date || user_email


2. POST api/v1/trips/{trip_id}/add-activity
Its working - added an activity id to a trip by the values:
Trip_id || xid


GET api/v1/trips/{trip_id}/activities
Its working - show all the activities of a specific trip (it returns the details of the activity not just the id)
